// <auto-generated />
namespace ES.Lab.Infrastructure.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Keychange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Keychange));
        
        string IMigrationMetadata.Id
        {
            get { return "201302271707359_Key change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
